const mongoose = require('mongoose');

const budgetSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  month: { type: Number, required: true },
  year: { type: Number, required: true },
  totalBudget: { type: Number, required: true },
  totalSpent: { type: Number, default: 0 },
  categories: [{
    name: { type: String, required: true },
    budgetedAmount: { type: Number, required: true },
    spentAmount: { type: Number, default: 0 },
    color: { type: String },
    icon: { type: String }
  }],
  savingsTarget: { type: Number, default: 0 },
  actualSavings: { type: Number, default: 0 },
  isAutoGenerated: { type: Boolean, default: false },
  status: { type: String, enum: ['active', 'completed', 'exceeded'], default: 'active' }
}, { timestamps: true });

budgetSchema.index({ userId: 1, year: 1, month: 1 }, { unique: true });

module.exports = mongoose.model('Budget', budgetSchema);
